### ISSUE TITLE
Cannot open menu (picture)

### ISSUE THREAD

**Issue by cryd-s** [Barma-lej/landroid-card#16]
## **Before submitting a bug**

[x ] I updated to the latest version available
[x ] I cleared the cache of my browser

## **Describe the bug**

I cannot open the conifgs like in the screenshot - only if i go to dashboard edit mode

## **Steps to reproduce**

Just insert the mower card 

## **Expected behavior**

i want to open the configs like in the old version

## **Screenshots**

![image](https://user-images.githubusercontent.com/47699362/182015939-0611c3d6-5b02-41d1-a2ce-cc6a4bac5006.png)

## **Versions:**

- Release: [ 0.2.1]
- Browser: [brave]
- HomeAssistant version: [ 2022.7.7]
- Landroid_cloud integration [ 2.3.0]

**Comment by Barma-lej** [comment]
**This is not a bug.**

Add to section `shortcuts` these entries:
```
  - name: Information
    service: input_boolean.toggle
    icon: mdi:information
    service_data:
      entity_id: input_boolean.mower_info_toggle
  - name: Einstellungen
    service: input_boolean.toggle
    icon: mdi:timer-settings
    service_data:
      entity_id: input_boolean.mower_sched_settings
```
