### ISSUE TITLE
No alues shown in Card for Blades and Worktime

### ISSUE THREAD

**Issue by Makana80** [Barma-lej/landroid-card#167]
I have installed Ver. 2.0.7 everything works pretty good. But i don´t see no values in stats. I i take a look in the entitie i can see need values for this. Can you help me pls^^
stats:
  default:
    - attribute: blades.total_on
      subtitle: Total blade time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: blades.current_on
      subtitle: Current blade time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: statistics.worktime_blades_on
      subtitle: Work time
      value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
    - attribute: statistics.distance
      value_template: '{{ (value | float(0) / 1000) | round(3) }}'
      unit: km
      subtitle: Distance

**Comment by Achronite** [comment]
+1
I'm also not seeing any values using the example config for stats.
![image](https://github.com/Barma-lej/landroid-card/assets/10363609/4714c832-1377-4181-8875-9a06bbf56108)
```
      - type: custom:landroid-card
        image: default
        compact_view: false
        show_status: true
        show_name: true
        show_toolbar: true        
        entity: vacuum.m500
        stats:
          default:
            - attribute: blades.total_on
              subtitle: Total blade time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: blades.current_on
              subtitle: Current blade time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: statistics.worktime_blades_on
              subtitle: Work time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: statistics.distance
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Distance
```
