### ISSUE TITLE
Yaw roll and pitch not showing when mowing

### ISSUE THREAD

**Issue by Phoenix-DH** [Barma-lej/landroid-card#313]
## **Before submitting a bug**

[x] I updated to the latest version available
[c] I cleared the cache of my browser. [See here](https://github.com/Barma-lej/landroid-card/issues/3#issuecomment-1176298240)

## **Describe the bug**

The valued are not updating …
![IMG_7699](https://github.com/Barma-lej/landroid-card/assets/44058592/32de5baf-66bb-4109-94d5-51de260033bf)

## **Steps to reproduce**

1. use the code from the example from this implementation

## **Expected behavior**

The values should live be updated.

## **Versions:**
All are latest

**Comment by Barma-lej** [comment]
It's not a bug

```
stats:
  default:
    - entity_id: sensor.mower_blades_total_on_time
      subtitle: Total blade time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
    - entity_id: sensor.mower_blades_current_on_time
      subtitle: Current blade time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
    - entity_id: sensor.mower_total_worktime
      subtitle: Work time
      value_template: '{{ as_timedelta((value | float(0) * 3600) | string ) }}'
    - entity_id: sensor.mower_distance_driven
      value_template: '{{ (value | float(0) / 1000) | round(3) }}'
      unit: km
      subtitle: Distance
  mowing:
    - entity_id: sensor.mower_yaw
      subtitle: Yaw
      unit: °
    - entity_id: sensor.mower_roll
      subtitle: Roll
      unit: °
    - entity_id: sensor.mower_pitch
      subtitle: Pitch
      unit: °
```

**Comment by Phoenix-DH** [comment]
I use exactly that, but during mowing I get this from the screenshot. When opening the details all is fine. Only on the main screen.

```
views:
  - title: Home
    badges: []
    cards:
      - type: custom:landroid-card
        image: default
        show_animation: true
        compact_view: false
        show_name: true
        show_status: true
        show_configbar: true
        show_toolbar: true
        entity: lawn_mower.james
        stats:
          default:
            - entity_id: sensor.james_blades_total_on_time
              subtitle: Arbeitszeit Messer total
              value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
            - entity_id: sensor.james_blades_current_on_time
              subtitle: Aktuelle Zeit Messer
              value_template: '{{ as_timedelta((value | float(0) * 3600) | string) }}'
            - entity_id: sensor.james_total_worktime
              subtitle: Arbeitszeit total
              value_template: '{{ as_timedelta((value | float(0) * 3600) | string ) }}'
            - entity_id: sensor.james_distance_driven
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Entfernung
            - entity_id: sensor.james_battery_total_charge_cycles
              subtitle: Ladezyklen
          mowing:
            - attribute: sensor.james_yaw
              subtitle: Yaw
              unit: °
            - attribute: sensor.james_roll
              subtitle: Roll
              unit: °
            - attribute: sensor.james_pitch
              subtitle: Pitch
              unit: °
```
