### ISSUE TITLE
Edgecut Button Not working

### ISSUE THREAD

**Issue by Cosmicbase** [Barma-lej/landroid-card#334]
## **Describe the bug**

Press button edgecut, no reaction.

## **Steps to reproduce**

Go to landroid card and click on edgecut.
No reaction.
Click on edgecut button at landroid integration it works.

## **Versions:**

- release: 1.1.0
- HomeAssistant version: 2024.4.3
- Landroid_cloud integration 5.0.2

**Comment by Barma-lej** [comment]
Yes. Since it's a button instead of service. I'll make it in further release

**Comment by Cosmicbase** [comment]
I'm glad to hear you're looking into this issue. Is there anything I can do to keep the button as a service? I find Edgecut very useful and would like to use it.

Thank so far for your good work.

**Comment by Cosmicbase** [comment]
When is the next release coming?
Or is there a way to install the pr #340 ?

**Comment by Barma-lej** [comment]
_Geduld, mein Freund, geduld_
Temporary you can use [`actions`](https://github.com/Barma-lej/landroid-card?tab=readme-ov-file#actions-object):
```
actions:
  edgecut:
    service: button.press
    service_data:
      entity_id: button.mower_start_cutting_edge
```
