### ISSUE TITLE
Help for integration image

### ISSUE THREAD

**Issue by JBa-5176** [Barma-lej/landroid-card#526]
Hello, I can't insert an image other than "default."
I created an image entity using card-image. Now, I have an image in the Image Upload folder, with an ID like qsjgrdffdge15ds2d952r9r84r/512x
or image.png using HA. I tried /media/local/filename, but nothing works. Can you explain?
Thanks.

And, a big thank you for your work in creating this tile.

**Comment by Barma-lej** [comment]
Add a picture:

* **Upload picture** lets you pick an image from the system used to show your Home Assistant UI.
* **Local path** lets you pick an image stored on Home Assistant. For example: `/homeassistant/images/lights_view_background_image.jpg`.

  - To store an image on Home Assistant, you need to [configure access to files](https://www.home-assistant.io/common-tasks/os/#configuring-access-to-files), for example via [Samba](https://www.home-assistant.io/common-tasks/os/#installing-and-using-the-samba-add-on) or the [Studio Code Server](https://www.home-assistant.io/common-tasks/os/#installing-and-using-the-visual-studio-code-vsc-add-on) add-on.

* **web URL** let you use an image from the web. For example https://www.home-assistant.io/images/frontpage/assist_wake_word.png.

**Comment by JBa-5176** [comment]
ok with URL , but impossible with local image !

![Image](https://github.com/user-attachments/assets/794c4889-99e1-4ab3-992f-92915fcdb869)

**Comment by Barma-lej** [comment]
What do you write as a local path?

**Comment by JBa-5176** [comment]
I have upload the file with  Medias / My Media ==> ok, no problem

![Image](https://github.com/user-attachments/assets/f2cb3fe8-ca88-4867-b168-4458f39d7628)

in your card, i try differents adresses :
 - /image.png
 - /media/image.png
 - /media/local/image.png
 - /homeassistant/image.png
 - /homeassistant/images/image.png
 - /local/image.png
 - etc.....

the file : image.png is in the folder **/media** , at the same level than **/homeassistant** (automatic by HAOS), 
!! ==> not under /homeassitant

![Image](https://github.com/user-attachments/assets/9c66c3dc-d824-4002-846c-448e248bac03)

**Comment by Barma-lej** [comment]
Read the [instruction](https://www.home-assistant.io/integrations/http/#hosting-files)

You need to put `image.png` in `/homeassistant/www/`.
The path to the image will be `/local/image.png`.

**Comment by JBa-5176** [comment]
i have create the file in this folder as yous say, but, no image on the card !

**Comment by Barma-lej** [comment]
Please publisch here your card config, screenshot from WinSCP and your image

```
image: /local/chromecast.png
image_size: "4"
show_animation: true
show_status: true
show_toolbar: true
entity: lawn_mower.mower
type: custom:landroid-card
shortcuts:
  - name: Notification
    service: input_boolean.toggle
    icon: mdi:bell
    service_data:
      entity_id: input_boolean.mower_views_switch
stats:
  default:
    - entity_id: sensor.mower_blades_total_on_time
      subtitle: Total blade time
      value_template: "{{ as_timedelta((value | float(0) * 3600) | round (0) | string) }}"
    - entity_id: sensor.mower_blades_current_on_time
      subtitle: Current blade time
      value_template: "{{ as_timedelta((value | float(0) * 3600) | round (0) | string) }}"
    - entity_id: sensor.mower_total_worktime
      subtitle: Work time
      value_template: "{{ as_timedelta((value | float(0) * 3600) | round (0) | string ) }}"
    - entity_id: sensor.mower_distance_driven
      value_template: "{{ (value | float(0) / 1000) | round(3) }}"
      unit: km
      subtitle: Distance
  mowing:
    - entity_id: sensor.mower_yaw
      subtitle: Yaw
      unit: °
    - entity_id: sensor.mower_roll
      subtitle: Roll
      unit: °
    - entity_id: sensor.mower_pitch
      subtitle: Pitch
      unit: °
settings:
  - switch.mower_party_mode
  - switch.mower_locked
  - number.mower_raindelay
  - number.mower_time_extension
  - number.mower_torque
  - select.mower_current_zone
  - button.mower_start_cutting_edge
  - button.mower_restart_baseboard
  - button.mower_reset_blade_time
  - button.mower_reset_charge_cycles
```

![Image](https://github.com/user-attachments/assets/e522fd83-a311-4d00-b7ce-962a77dd27e3)
