### ISSUE TITLE
Formatting Date&Time of Next Start

### ISSUE THREAD

**Issue by Swimmer71** [Barma-lej/landroid-card#528]
Hi,
don't know exactly when it changed, but now I see a not so nice to read formatting of the "next start" Date and Time format. And the time should be 14:00, so why it shows 12:00 +00:00
In the past it was something like "22.04.2025 14:00".
How can I change this back again?

![Image](https://github.com/user-attachments/assets/11bb2e68-c442-4ec5-981d-ce2ce5d090af)

The entity "next scheduled start" itself looks like:

![Image](https://github.com/user-attachments/assets/f989b1ed-b69b-4c72-a237-7231785812e4)

**Comment by Swimmer71** [comment]
Really nobody any idea?

**Comment by Barma-lej** [comment]
Unfortunately, I can't reproduce the problem. Can you check if everything is set correctly in your user's profile?
[![Open your Home Assistant instance and show your Home Assistant user's profile.](https://my.home-assistant.io/badges/profile.svg)](https://my.home-assistant.io/redirect/profile/)

![Image](https://github.com/user-attachments/assets/1bebe6ee-7d2f-4a93-9ffe-efe2e07b66f9)

**Comment by Swimmer71** [comment]
Here are my settings:
They are the same as yours
![Image](https://github.com/user-attachments/assets/16e5bb85-85c8-4bc1-9907-fa70b6c6c641)

**Comment by Swimmer71** [comment]
But in former versions the format was ok, so this must be changed in one of the last versions, don't know exactely when

**Comment by Barma-lej** [comment]
Can you publish your config here?

**Comment by Swimmer71** [comment]
Right now I am on lonesome Beaches in Greece, but I will try with mobile phone

**Comment by Swimmer71** [comment]
```
image: default
image_size: "2"
show_animation: true
show_status: true
show_toolbar: true
type: custom:landroid-card
entity: lawn_mower.rasenmaher
compact_view: false
show_name: true
image_left: true
stats:
  default:
    - entity_id: sensor.rasenmaher_distance_driven
      value_template: "{{ value |float(0) |round(0) }}"
      unit: km
      subtitle: Distance
    - entity_id: sensor.rasenmaher_blades_total_on_time
      subtitle: Schnitt
      value_template: "{{ value |float(0) |round(0) }}"
      unit: h
    - entity_id: sensor.rasenmaher_blades_current_on_time
      subtitle: Schnitt
      value_template: "{{ value |float(0) |round(0) }}"
      unit: h
    - entity_id: button.rasenmaher_restart_baseboard
      subtitle: Reset
      value_template: <--
  mowing:
    - entity_id: sensor.rasenmaher_daily_progress
      subtitle: Erledigt
      unit: "%"
    - entity_id: sensor.rasenmaher_yaw
      subtitle: Yaw
      unit: °
    - entity_id: sensor.rasenmaher_roll
      subtitle: Roll
      unit: °
    - entity_id: sensor.rasenmaher_pitch
      subtitle: Pitch
      unit: °
settings:
  - switch.rasenmaher_party_mode
  - number.rasenmaher_raindelay
  - number.rasenmaher_torque
  - button.rasenmaher_start_cutting_edge
  - button.rasenmaher_restart_baseboard
```

**Comment by Swimmer71** [comment]
![Image](https://github.com/user-attachments/assets/406637d3-f5b1-4c4e-8b38-af9ab098b031)

**Comment by Swimmer71** [comment]
could you find anything? Is it maybe an issue of landroid cloud and not card?

**Comment by Barma-lej** [comment]
I can't find anything yet. Does it look like this on the computer too? 

This is what it looks like for me with your configuration:

![Image](https://github.com/user-attachments/assets/b9d744f1-ffb1-44e7-8dac-5e8579b91ab4)

**Comment by Swimmer71** [comment]
very strange, your format is the one which I want back again 🤩. On PC it looks same as on Android phone. I use landroid cloud Integration 5.2.7 and card version is 1.2.4

**Comment by Swimmer71** [comment]
I just reloaded both, landroid cloud and card, but even after reboot, no change. I even made a new Landroid card.....

**Comment by Swimmer71** [comment]
what I don't understand is, that the entity 'next scheduled start' is formatted correctly (see first post)

**Comment by Barma-lej** [comment]
Please try installing an older version of Landroid Card and tell me which version is correct.

**Comment by Swimmer71** [comment]
Hi, I think you closed this too early. I turned on the worx mower this year the first time and the next start format is back. At the end of last season it was ok, because I found out this happens when using German Umlauts in entity name. I removed them last year and then it was ok, but now it's back 

![Image](https://github.com/user-attachments/assets/bf126a32-73d0-486d-af05-2d7732b433ab)

**Comment by Barma-lej** [comment]
Closing due to inactivity.

I still can’t reproduce this on my side, and I’m not able to repeat the behavior described in this issue. So far, nobody else has confirmed the same behavior either.

For reference, here is a screenshot from my setup:

<img width="501" height="427" alt="Image" src="https://github.com/user-attachments/assets/653c6016-3782-4dd2-9424-fb5a98384258" />

**Comment by Barma-lej** [comment]
Hi @Swimmer71,

Thank you for the additional info — the Umlauts hint is very helpful! 🙏

I investigated the code and found a potential issue in how the date comparison is done:

```js
// Current code (potentially problematic)
Date.parse(new Date()) < Date.parse(nextScheduledStart.state)
```

`Date.parse(new Date())` is an antipattern — `Date.parse()` expects a string, not a `Date` object. In some environments this can produce unexpected results. I'll fix this in the next release:

```js
// Fixed
Date.now() < new Date(nextScheduledStart.state).getTime()
```

---

**However**, the actual display format (`12:00 +00:00` instead of `14:00`) suggests a **timezone issue**, not a code bug. The sensor `next_schedule` stores the timestamp in UTC (`+00:00`), and `hass.formatEntityState()` is supposed to convert it to your local timezone automatically — but something prevents that in your setup.

**Please check the following:**

1. **Home Assistant timezone** — go to **Settings → System → General** and verify that your server timezone is set correctly (e.g., `Europe/Berlin`).

2. **User profile language & timezone** — go to your [profile page](https://my.home-assistant.io/redirect/profile/) and check that **Language** and **Time zone** (under "Customization") are set correctly. The "Auto detect" option sometimes picks up wrong values.

3. **Browser timezone** — open your browser console and run:
   ```js
   Intl.DateTimeFormat().resolvedOptions().timeZone
   ```
   It should match your local timezone.

4. **Umlauts connection** — you mentioned the issue appeared when the device name contained Umlauts (ä, ö, ü) and disappeared after removing them. This is unexpected, as Umlauts should not affect date formatting. Could you try **renaming your mower back to a name with Umlauts** and confirm if the problem reappears? This would help narrow down the root cause.

5. **Share the state of the sensor** — open Developer Tools → States, find `sensor.[mower_name]_next_schedule` (or similar) and share the full state value, e.g. `2026-04-10T12:00:00+00:00`. This will confirm whether the timezone offset is already wrong at the sensor level (Landroid Cloud issue) or only in the card display.

---

If the sensor itself already shows the wrong time, the issue is in the **Landroid Cloud integration**, not in this card. In that case, please open an issue at [MTrab/landroid_cloud](https://github.com/MTrab/landroid_cloud).

Thanks for your patience! 🌿

**Comment by Swimmer71** [comment]
In devtool the date format is already displayed wrong

![Image](https://github.com/user-attachments/assets/8e871424-2028-4b01-abce-e53cd729f062)

And it makes no difference when I change the timezone/language/.... manual, and Browser has correct tomezone

<img width="488" height="187" alt="Image" src="https://github.com/user-attachments/assets/1fb38f28-12ef-4c69-bdbd-9111cee1a071" />

Last year I also reported this behavior to Marlene Trapp. And as I said before: last summer this behavior disappeared when I removed the Umlauts form Entity name and the rest of the summer it worked. Now this is back again and I still use no Umlauts.

**Comment by Barma-lej** [comment]
Hi @Swimmer71,

Since your sensor also has `device_class: timestamp` and the raw ISO string is already shown in Dev Tools, the issue is not in the integration or the card itself — it's somewhere in how `hass.formatEntityState()` resolves the locale or timezone in your specific setup.

Please open your browser console on the HA page and run the following:

```js
const hass = document.querySelector('home-assistant').hass;
console.log('locale:', JSON.stringify(hass.locale));
console.log('time_zone:', hass.config.time_zone);
console.log('formatEntityState result:', hass.formatEntityState(hass.states['sensor.robby_next_scheduled_start']));
```

> ⚠️ Replace `sensor.robby_next_scheduled_start` with the actual entity ID of your next schedule sensor if it differs.

Please share the full output — this will tell us exactly where the formatting breaks.

<img width="1190" height="558" alt="Image" src="https://github.com/user-attachments/assets/7aa3d453-0cb8-4271-8e79-a7b708e2ac1d" />

**Comment by Swimmer71** [comment]
<img width="1059" height="215" alt="Image" src="https://github.com/user-attachments/assets/668cbe36-b109-4bf3-a35f-58dd2c58649f" />

Just updated the landroid cloud integration to latest BETA, deleted mover and reintegrated it new. Now all entitiy names are in german....

**Comment by Barma-lej** [comment]
Then you can update Landroid Card 2026.4.0-beta

**Comment by Swimmer71** [comment]
changed const from hass to hasss:

<img width="1287" height="241" alt="Image" src="https://github.com/user-attachments/assets/84227ef9-b888-415f-a33d-2aafc857bbc4" />

**Comment by Swimmer71** [comment]
Server settings:

<img width="464" height="463" alt="Image" src="https://github.com/user-attachments/assets/8e0543fe-9d73-48e5-a24f-1cff5340874c" />

user setting:

<img width="470" height="437" alt="Image" src="https://github.com/user-attachments/assets/54fa5f85-59f2-4923-a39b-7b3f25bfa846" />

**Comment by Barma-lej** [comment]
<img width="1218" height="1364" alt="Image" src="https://github.com/user-attachments/assets/32d9a46d-aaf1-4349-8d27-7a3757efc36e" />

<img width="1210" height="1152" alt="Image" src="https://github.com/user-attachments/assets/cc2cb7c3-4b6f-4884-b53e-3fa69ea20048" />

**Comment by Barma-lej** [comment]
<img width="1188" height="1220" alt="Image" src="https://github.com/user-attachments/assets/9d39831f-39da-400b-9c11-11903219abfb" />

**Comment by Swimmer71** [comment]
Changed now everything to exactly your settings (sogar Österreich zu Deutschland ;-) ):

<img width="850" height="1764" alt="Image" src="https://github.com/user-attachments/assets/109cbee1-3fa9-4b91-ab46-66c23d7d8867" />

<img width="909" height="939" alt="Image" src="https://github.com/user-attachments/assets/7d0b8841-71a5-46c1-99ec-63acf9c9ccae" />

**Comment by Swimmer71** [comment]
Result:

<img width="668" height="336" alt="Image" src="https://github.com/user-attachments/assets/07457f5b-efbb-4e84-a331-b2ba1e382708" />

**Comment by Swimmer71** [comment]
The more info of the entity itself shows the correct format:
Any idea what the problem is here?
<img width="867" height="364" alt="Image" src="https://github.com/user-attachments/assets/b134a116-1d85-41f6-bd15-ca61356228fb" />

**Comment by Barma-lej** [comment]
Try to update yout Home Assistant, I don'n t have any idea

**Comment by Swimmer71** [comment]
update to what? I am always up to date🤷

**Comment by Swimmer71** [comment]
So, finally I found the problem:
In customize_globe.yaml I added:
```
sensor.schaf*:
  state_class: none

```
to opt out from long term statistik, but when I do this, the date format is not local anymore. After removing this from file, it is ok!

<img width="347" height="192" alt="Image" src="https://github.com/user-attachments/assets/ab1df9d8-b4da-4dd4-810c-205d6709e8f0" />

Is this behavior normal?

**Comment by Barma-lej** [comment]
This is actually expected behavior. When you override entity attributes via `customize_glob.yaml`, you can accidentally interfere with how Home Assistant interprets the entity.

Setting `state_class: none` on a timestamp sensor causes HA to lose the context needed to format the state correctly — `hass.formatEntityState()` relies on `device_class` and `state_class` together to determine the output format. Overriding `state_class` breaks that chain.

**The correct way to exclude a sensor from long-term statistics** without touching its attributes is to use `recorder` config in `configuration.yaml`:
```yaml
recorder:
  exclude:
    entities:
      - sensor.schaf_next_schedule
```

This excludes it from the recorder/statistics without modifying the entity's attributes, so `device_class: timestamp` stays intact and the date format remains correct.
