### ISSUE TITLE
Trouble installing: Custom element doesn’t exist: landroid-card

### ISSUE THREAD

**Issue by roofburner** [Barma-lej/landroid-card#68]
Dear,

I'm trying to install the Barma-lej card, but I'm getting this error: "Custom element doesn’t exist: landroid-card."

I'm using Lovelace in YAML mode.

I have installed your custom repo and it appears in my HACS - Frontend as "Landroid Cloud". Correct?

Here's my file located:
```
/usr/share/homeassistant# ll www/community/landroid-card/
total 548
drwxr-xr-x 2 root root   4096 Oct  4 21:45 ./
drwxr-xr-x 6 root root   4096 Oct  4 21:45 ../
-rw-r--r-- 1 root root 408647 Oct  4 21:45 landroid-card.js
-rw-r--r-- 1 root root 141830 Oct  4 21:45 landroid-card.js.gz
```

I included this in my ui-lovelace.yaml:
```
resources:
  - url: /hacsfiles/landroid-card/landroid-card.js
    type: module
```
My Landroid Cloud seems to work, as the entity vacuum.mower appears in my Developer Tools

I ran a debug, but it doesn't seem to throw an error on the card setup/usage.

What are my options?

**Comment by Barma-lej** [comment]
Use HACS please

**Comment by roofburner** [comment]
I use HACS. I added your repo via https://hacs.xyz/docs/faq/custom_repositories/

**Comment by Barma-lej** [comment]
You don't need to include in your ui-lovelace.yaml.
Can you see the landroid-card in your HACS?

**Comment by roofburner** [comment]
Yes, I do. It appears in HACS -> Frontend -> Landroid Card.
I'm using Lovelace in YAML mode. How do I import the card?
I cannot edit the dashboard: "The edit UI is not available when in YAML mode."

**Comment by Barma-lej** [comment]
Try to force clear browser cache

> I cannot edit the dashboard: "The edit UI is not available when in YAML mode."

https://community.home-assistant.io/t/the-edit-ui-is-not-available-when-in-yaml-mode/370290

**Comment by roofburner** [comment]
I have access my home assistant though a private brower (chrome and firefox). Still no card.
How can I be sure the js is loaded?

**Comment by roofburner** [comment]
I don't know much about Chrome debug (F12) but I don't see the js loaded:

![afbeelding](https://user-images.githubusercontent.com/360846/193919945-3a69e999-1c1d-4297-863c-ff5081cc4e75.png)

**Comment by Barma-lej** [comment]
![Screenshot 2022-10-04 222902](https://user-images.githubusercontent.com/34010886/193920338-ce4f6201-c47b-4793-a3b6-8df35de8ad6f.jpg)

**Comment by roofburner** [comment]
It look like the js isn't loaded:
![afbeelding](https://user-images.githubusercontent.com/360846/193920898-1c15bf02-b8cf-4cf4-b7a2-e6e13435ed05.png)

**Comment by Barma-lej** [comment]
I hope do you installed the card?

**Comment by roofburner** [comment]
I hope you mean this by installing:

I copied this https://github.com/Barma-lej/landroid-card/releases/download/0.2.3/landroid-card.js to www/community/landroid-card/

I included this in ui-lovelace.yaml.

```
resources:
  - url: /local/community/landroid-card/landroid-card.js
    type: module
```
I also included the card in ui-lovelace, as I did for my other cards:
```
view
  - icon: mdi:robot-mower-outline
    title: Landroid
    id: landroid
    cards:
      - type: "custom:landroid-card"
        image: default
        compact_view: false
        show_status: true
        show_name: true
        show_toolbar: true
        entity: vacuum.mower
        stats:
          default:
            - attribute: blades.total_on
              subtitle: Total blade time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: blades.current_on
              subtitle: Current blade time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: statistics.worktime_blades_on
              subtitle: Work time
              value_template: '{{ as_timedelta((value | float(0) * 60) | string) }}'
            - attribute: statistics.distance
              value_template: '{{ (value | float(0) / 1000) | round(3) }}'
              unit: km
              subtitle: Distance
          mowing:
            - attribute: orientation.yaw
              subtitle: Yaw
              unit: °
            - attribute: orientation.roll
              subtitle: Roll
              unit: °
            - attribute: orientation.pitch
              subtitle: Pitch
              unit: °
        shortcuts:
          - name: Notification
            service: automation.toggle
            icon: mdi:bell
            service_data:
              entity_id: automation.mower_notify_status
```
